USE AiResumeStudioDb;

SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE';

SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_NAME LIKE 'PK%';

SELECT 
    TABLE_NAME      AS [Table],
    COLUMN_NAME     AS [Column],
    DATA_TYPE       AS [Data Type],
    CHARACTER_MAXIMUM_LENGTH AS [Max Length],
    IS_NULLABLE     AS [Nullable],
    COLUMN_DEFAULT  AS [Default Value]
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_NAME IN ('Resumes', 'Educations', 'WorkExperiences', 'Skills', 'ResumeAnalyses', 'AspNetUsers')
ORDER BY 
    TABLE_NAME, ORDINAL_POSITION;

    SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Skills';